### ISSUE TITLE
Blank or none file output

### ISSUE THREAD

**Issue by ACShaw1989** [Nicolik/MESCnn#1]
Hello! I am very intersted in your team's article because it may provide an objective tool to evaluate the biospy picture and return a quantified score. So, I installed the packages and try to apply it in scoring the pictures. 
However, after installing all applications on PC(win10), I got nothing in the folders after running these code(run_project_tif.py, run_wsi_tif.py, run _wsi_tif_all.py). I could not figure out where this problem occured because there was no WARNNING or other error was reported. 
This picture shows that the folder(.\MESCnn-main\Data\Export\cascade_R_50_FPN_3x) occupys 0 Bytes after the code(run_wsi_tif.py) running by Jupyter. 
![image](https://github.com/Nicolik/MESCnn/assets/149562805/9c6510fb-7320-4de0-adea-1041178a5627)
This picture shows no WARNNING in the progression. 
![image](https://github.com/Nicolik/MESCnn/assets/149562805/a7d2632e-50c3-4547-8597-7133f0d194f0)
Could the OS would be the problem? My OS is Windows10. 
I really appreciate it if you could give me response. Best wishes.

**Comment by Nicolik** [comment]
Hi!
Thanks for reporting this.
We put the install guidelines for Ubuntu, but is definitively possible to install and use MESCnn on Windows (Detectron2 installation on Windows is a bit tricky and can cause some issues).
Can you check if it is exporting something in the directory of the env (\envs\mescnn-env\mescnn-main\Data)? 
Also, perhaps you should try outside of notebook, so that we can read the output of every program of the pipeline and see which one may have problems.
Please note that WSIs must be split into tiles with PathMESCnn.TILE before using PathMESCnn.SEGMENT.

**Comment by ACShaw1989** [comment]
Hi!
Thank you for your reply! I tried using VSCode to run the code then I found that the uncorrect installation of openslide on win10 might be the problem. When importing openslide in test_tile, returned:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Applications\anaconda3\envs\MESCnn-Env\lib\site-packages\openslide\__init__.py", line 30, in <module>
    from openslide import lowlevel
  File "D:\Applications\anaconda3\envs\MESCnn-Env\lib\site-packages\openslide\lowlevel.py", line 59, in <module>
    _lib = cdll.LoadLibrary('libopenslide-0.dll')
  File "D:\Applications\anaconda3\envs\MESCnn-Env\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "D:\Applications\anaconda3\envs\MESCnn-Env\lib\ctypes\__init__.py", line 364, in __init__    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。#The specified module could not be found
```

So I add the code in the _~\MESCnn-Env\lib\site-packages\openslide\lowlevel.py_ :
```
import os
os.environ['PATH'] = "D:\\Applications\\openslide-win64-20231011\\bin" + ";" + os.environ['PATH']  
```
But still report same problem. I guess it might because I downloaded the latest version of Openslide(openslide-win64-20231011, v4.0.0), so i tried download the old version(openslide-win64-20220806, v3.4.1) and change the PATH, then the code run. 
The picture shows the content in the temp folder when the code running after the correction:
![image](https://github.com/Nicolik/MESCnn/assets/149562805/228985a0-9946-4133-859b-b0d2934734aa)

Thank you for your reply! If I meet other problems, I will comment later.

**Comment by Nicolik** [comment]
I am happy that is running now!
Since the problem looks solved, I will close this issue. 
You can open another one if some specific problem arises.
